### PR TITLE
Fix convert_checkpoint errors

### PR DESCRIPTION
**Pull request by hiroshi-matsuda-rit**

### CODE REVIEW

**Comment by conglongli** [comment]
Hi Matsuda-san @hiroshi-matsuda-rit I think I got automatically assigned as reviewer because of the CODEOWNERS file forked from microsoft/Megatron-DeepSpeed. Could you help to delete this file in this PR? https://github.com/llm-jp/Megatron-DeepSpeed/blob/main/CODEOWNERS Thank you so much!

**Comment by hiroshi-matsuda-rit** [comment]
@conglongli I am very sorry for unintentionally assigning you as a reviewer.

**Comment by conglongli** [comment]
> @conglongli I am very sorry for unintentionally assigning you as a reviewer.

@hiroshi-matsuda-rit No worries at all and it's not your fault :) We have the same CODEOWNERS file in our repos (such as https://github.com/microsoft/Megatron-DeepSpeed/blob/main/CODEOWNERS) to automatically assign team members as reviewers. I thought that for forked repo it shouldn't trigger, but maybe it's because I also joined https://github.com/llm-jp. Anyway, if we could remove https://github.com/llm-jp/Megatron-DeepSpeed/blob/main/CODEOWNERS, the automatic reviewer assignment will stop.

**Comment by hiroshi-matsuda-rit** [comment]
@conglongli I just deleted the entries in CODEOWNERS.

**Pull request merged**
